# Generated by Django 3.0.5 on 2020-05-06 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='专业编码')),
                ('name', models.CharField(max_length=100, verbose_name='专业全称')),
                ('jc', models.CharField(max_length=50, verbose_name='专业简称')),
            ],
            options={
                'verbose_name_plural': '专业',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='年级编码')),
                ('name', models.CharField(max_length=100, verbose_name='年级全称')),
                ('jc', models.CharField(max_length=50, verbose_name='年级简称')),
            ],
            options={
                'verbose_name_plural': '年级',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='院系编码')),
                ('name', models.CharField(max_length=100, verbose_name='院系全称')),
                ('jc', models.CharField(max_length=50, verbose_name='院系简称')),
            ],
            options={
                'verbose_name_plural': '院系',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='班级编码')),
                ('name', models.CharField(max_length=100, verbose_name='班级全称')),
                ('jc', models.CharField(max_length=50, verbose_name='班级简称')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Department', verbose_name='所属专业')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Grade', verbose_name='所在年级')),
            ],
            options={
                'verbose_name_plural': '班级',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='姓名')),
                ('code', models.CharField(max_length=50, verbose_name='学号')),
                ('tushu_flag', models.BooleanField(verbose_name='是否正常还书')),
                ('caiwu_flag', models.BooleanField(verbose_name='是否缴费')),
                ('sushe_flag', models.BooleanField(verbose_name='是否退宿')),
                ('grad_flag', models.BooleanField(verbose_name='是否已发放毕业证')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Team', verbose_name='所属班级')),
            ],
            options={
                'verbose_name_plural': '毕业生信息',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.School', verbose_name='所属院系'),
        ),
    ]
