# Generated by Django 3.0.5 on 2020-04-27 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_text', models.CharField(max_length=200)),
                ('school_jc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_code', models.CharField(max_length=50)),
                ('enter_year', models.IntegerField()),
                ('graduate_year', models.IntegerField()),
                ('tushu_flag', models.BooleanField(verbose_name='图书是否正常')),
                ('caiwu_flag', models.BooleanField(verbose_name='是否欠费')),
                ('sushe_flag', models.BooleanField(verbose_name='是否退宿')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.School')),
            ],
        ),
    ]
